[package]
name = "imgurian"
version = "0.1.0"
edition = "2018"

[dependencies]
base64 = "0.13.0"
reqwest = { version = "0.11.6" }
serde = "1.0.130"
serde_json = "1.0.69"
serde_path_to_error = "0.1.5"

[dev-dependencies]
tokio = { version = "1.13.0", features = ["rt-multi-thread", "macros"] }
wiremock = "0.5.8"
