name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    uses: r7kamura/workflows/.github/workflows/github-release.yml@main
    secrets:
      github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    uses: r7kamura/workflows/.github/workflows/rust-cargo-publish.yml@main
    secrets:
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
