name: tag

on:
  push:
    branches:
      - main
    paths:
      - Cargo.toml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: cargo read-manifest | jq -r .version
