name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chetan/git-restore-mtime-action@v1.1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
            target/
          key: ${{ runner.os }}-cargo-v3-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup component add clippy rustfmt
      - uses: r7kamura/rust-problem-matchers@v1
      - run: cargo fmt -- --check
      - run: cargo build
      - run: cargo clippy -- -D warnings
